{
  "formatVersion": "1.1",
  "component": {
    "group": "com.stroeer.ads",
    "module": "core",
    "version": "1.0.0-rc3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.prebid",
          "module": "prebid-mobile-sdk",
          "version": {
            "requires": "3.3.4"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "24.6.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.14.0"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference-ktx",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-1.0.0-rc3.aar",
          "url": "core-1.0.0-rc3.aar",
          "size": 749321,
          "sha512": "f22d06ba919ecad031c0207364dcc44aef480febe589c70b3b35efbfc5bf37eb60d21f11ff76d1e2980b892d55979b461daef8d4d3ed94e4b5ad64e246048fa2",
          "sha256": "7458ffcdb90b74d66a5cd843664e5f3439e4097d0195c7e28f786754445fa246",
          "sha1": "9afae42512a0a4f571fb5b7ed62687514296dad2",
          "md5": "fbb5c27a68bad231f053649609a5cf53"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.iabtcf",
          "module": "iabtcf-decoder",
          "version": {
            "requires": "2.0.10"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.nanohttpd",
          "module": "nanohttpd",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "org.prebid",
          "module": "prebid-mobile-sdk",
          "version": {
            "requires": "3.3.4"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "24.6.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.14.0"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference-ktx",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-1.0.0-rc3.aar",
          "url": "core-1.0.0-rc3.aar",
          "size": 749321,
          "sha512": "f22d06ba919ecad031c0207364dcc44aef480febe589c70b3b35efbfc5bf37eb60d21f11ff76d1e2980b892d55979b461daef8d4d3ed94e4b5ad64e246048fa2",
          "sha256": "7458ffcdb90b74d66a5cd843664e5f3439e4097d0195c7e28f786754445fa246",
          "sha1": "9afae42512a0a4f571fb5b7ed62687514296dad2",
          "md5": "fbb5c27a68bad231f053649609a5cf53"
        }
      ]
    }
  ]
}
