{
  "formatVersion": "1.1",
  "component": {
    "group": "com.stroeer.ads",
    "module": "cmp",
    "version": "1.0.0-rc1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "cmp-1.0.0-rc1.aar",
          "url": "cmp-1.0.0-rc1.aar",
          "size": 28064,
          "sha512": "344cc08a6ef80745bc2b328fe67d07053701915f23fd5ddb2ce8b049b454b346a466595b277106ec65f730312517320ce6dc573915b3e7ee4354288050a996de",
          "sha256": "040006a120a9fba0408cc540a9c8a2ffa050a405d1cd33b114c7397dc448453a",
          "sha1": "2f603d1fd2e2d9c719457163d35556b19f63af16",
          "md5": "310693952348b58e4b70a8535e37a306"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.stroeer.ads",
          "module": "core",
          "version": {
            "requires": "1.0.0-rc1"
          }
        },
        {
          "group": "com.sourcepoint.cmplibrary",
          "module": "cmplibrary",
          "version": {
            "requires": "7.15.13"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "cmp-1.0.0-rc1.aar",
          "url": "cmp-1.0.0-rc1.aar",
          "size": 28064,
          "sha512": "344cc08a6ef80745bc2b328fe67d07053701915f23fd5ddb2ce8b049b454b346a466595b277106ec65f730312517320ce6dc573915b3e7ee4354288050a996de",
          "sha256": "040006a120a9fba0408cc540a9c8a2ffa050a405d1cd33b114c7397dc448453a",
          "sha1": "2f603d1fd2e2d9c719457163d35556b19f63af16",
          "md5": "310693952348b58e4b70a8535e37a306"
        }
      ]
    }
  ]
}
