{
  "formatVersion": "1.1",
  "component": {
    "group": "com.stroeer.ads",
    "module": "cmp",
    "version": "1.0.0-rc2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "cmp-1.0.0-rc2.aar",
          "url": "cmp-1.0.0-rc2.aar",
          "size": 28068,
          "sha512": "3cc76860129b70d037be289740697d3160bfaec984475b880e87cc1d91995e6a65b5c8abcdfcc94be87b6a3298261d38d385d3874091a6483997a2e9bda8668a",
          "sha256": "f55e64f2c8d146bebceece74082026ca74ebe68f895249f8d604a6aeaa9995bb",
          "sha1": "683b952b303711b28c7acc639e944e783b7dbb87",
          "md5": "91b5ff050035dc0aa59235a3a3696ead"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.stroeer.ads",
          "module": "core",
          "version": {
            "requires": "1.0.0-rc2"
          }
        },
        {
          "group": "com.sourcepoint.cmplibrary",
          "module": "cmplibrary",
          "version": {
            "requires": "7.15.13"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "cmp-1.0.0-rc2.aar",
          "url": "cmp-1.0.0-rc2.aar",
          "size": 28068,
          "sha512": "3cc76860129b70d037be289740697d3160bfaec984475b880e87cc1d91995e6a65b5c8abcdfcc94be87b6a3298261d38d385d3874091a6483997a2e9bda8668a",
          "sha256": "f55e64f2c8d146bebceece74082026ca74ebe68f895249f8d604a6aeaa9995bb",
          "sha1": "683b952b303711b28c7acc639e944e783b7dbb87",
          "md5": "91b5ff050035dc0aa59235a3a3696ead"
        }
      ]
    }
  ]
}
