{
  "formatVersion": "1.1",
  "component": {
    "group": "com.stroeer.ads",
    "module": "compose",
    "version": "1.0.0-rc1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "compose-1.0.0-rc1.aar",
          "url": "compose-1.0.0-rc1.aar",
          "size": 47946,
          "sha512": "ce91525489ac18304121f1beab8772ffcaec64e110acacb3cf61518d955f9631c212b627087810994a629ce6be9b448ea50bead5c6737f2f9cdb34370444a46c",
          "sha256": "b07eb4e18245878cffc3e8910b0ffba485d98b255128a75cd5a543c80bd5ec15",
          "sha1": "96ba0b435f5778f60d0e7f053cbc914b336cca09",
          "md5": "ae304df91b40a94da73e2671522efd7a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.stroeer.ads",
          "module": "core",
          "version": {
            "requires": "1.0.0-rc1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.11.4"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "compose-1.0.0-rc1.aar",
          "url": "compose-1.0.0-rc1.aar",
          "size": 47946,
          "sha512": "ce91525489ac18304121f1beab8772ffcaec64e110acacb3cf61518d955f9631c212b627087810994a629ce6be9b448ea50bead5c6737f2f9cdb34370444a46c",
          "sha256": "b07eb4e18245878cffc3e8910b0ffba485d98b255128a75cd5a543c80bd5ec15",
          "sha1": "96ba0b435f5778f60d0e7f053cbc914b336cca09",
          "md5": "ae304df91b40a94da73e2671522efd7a"
        }
      ]
    }
  ]
}
