{
  "formatVersion": "1.1",
  "component": {
    "group": "com.stroeer.ads",
    "module": "confiant",
    "version": "1.0.0-rc1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "confiant-1.0.0-rc1.aar",
          "url": "confiant-1.0.0-rc1.aar",
          "size": 6289,
          "sha512": "6ddcf2972de098edc76318a9b508f1e713f6ab6666b31538cf797bf7b407eb943671cdb0eb9a543ee2588ae627e73a94d8a43cb30fa4ad2bf998df349f951067",
          "sha256": "87119721d18e04088e0835fb5d6f0f6a05535bd9e4bb228819c9c5429a7e492c",
          "sha1": "7bac9d8bb0e98be3b997e5368e60a5d672a39ad8",
          "md5": "a8fdf25e04b63c03d700028b203abfc9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.stroeer.ads",
          "module": "core",
          "version": {
            "requires": "1.0.0-rc1"
          }
        },
        {
          "group": "com.confiant.android",
          "module": "sdk",
          "version": {
            "requires": "6.1.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "confiant-1.0.0-rc1.aar",
          "url": "confiant-1.0.0-rc1.aar",
          "size": 6289,
          "sha512": "6ddcf2972de098edc76318a9b508f1e713f6ab6666b31538cf797bf7b407eb943671cdb0eb9a543ee2588ae627e73a94d8a43cb30fa4ad2bf998df349f951067",
          "sha256": "87119721d18e04088e0835fb5d6f0f6a05535bd9e4bb228819c9c5429a7e492c",
          "sha1": "7bac9d8bb0e98be3b997e5368e60a5d672a39ad8",
          "md5": "a8fdf25e04b63c03d700028b203abfc9"
        }
      ]
    }
  ]
}
