{
  "formatVersion": "1.1",
  "component": {
    "group": "com.stroeer.ads",
    "module": "confiant",
    "version": "1.0.0-rc2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "confiant-1.0.0-rc2.aar",
          "url": "confiant-1.0.0-rc2.aar",
          "size": 6290,
          "sha512": "d3c996eb6d87b15640ead820d6e5401e7a96d1d100f49bf9ce64631d37277a1ea5bb607bf105751d79fec729e6ad99d191e97c7ef2b670f5949604087c7eb2fc",
          "sha256": "be850d114612c0ba8b439d63614ba10b92a9a45a55c700bc5088ca00d54fc7fe",
          "sha1": "68c6c9a1d2e294564c9e269e9876dff6bea0063b",
          "md5": "66fa9d5e093c44f00342c8efe290b196"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.stroeer.ads",
          "module": "core",
          "version": {
            "requires": "1.0.0-rc2"
          }
        },
        {
          "group": "com.confiant.android",
          "module": "sdk",
          "version": {
            "requires": "6.1.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "confiant-1.0.0-rc2.aar",
          "url": "confiant-1.0.0-rc2.aar",
          "size": 6290,
          "sha512": "d3c996eb6d87b15640ead820d6e5401e7a96d1d100f49bf9ce64631d37277a1ea5bb607bf105751d79fec729e6ad99d191e97c7ef2b670f5949604087c7eb2fc",
          "sha256": "be850d114612c0ba8b439d63614ba10b92a9a45a55c700bc5088ca00d54fc7fe",
          "sha1": "68c6c9a1d2e294564c9e269e9876dff6bea0063b",
          "md5": "66fa9d5e093c44f00342c8efe290b196"
        }
      ]
    }
  ]
}
