{
  "formatVersion": "1.1",
  "component": {
    "group": "com.stroeer.ads",
    "module": "compose",
    "version": "1.0.0-rc2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "compose-1.0.0-rc2.aar",
          "url": "compose-1.0.0-rc2.aar",
          "size": 47943,
          "sha512": "30b7a876604d2d702297a0dc724b824b76742fde43003f79387fe6c358ff192b34fd5e76a2ab1ed43e01e7c9442d66089633a70cf4206532d2de566fcc6668e4",
          "sha256": "22acdcbc68b65c0428b2b3c862ace97445e9e1493b61e0c271b9fa33d482be6b",
          "sha1": "c78daf510c86c0951e7b618d67b058210aa163c8",
          "md5": "42acf36c4c816532facc7c039c4edc2d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.stroeer.ads",
          "module": "core",
          "version": {
            "requires": "1.0.0-rc2"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.11.4"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "compose-1.0.0-rc2.aar",
          "url": "compose-1.0.0-rc2.aar",
          "size": 47943,
          "sha512": "30b7a876604d2d702297a0dc724b824b76742fde43003f79387fe6c358ff192b34fd5e76a2ab1ed43e01e7c9442d66089633a70cf4206532d2de566fcc6668e4",
          "sha256": "22acdcbc68b65c0428b2b3c862ace97445e9e1493b61e0c271b9fa33d482be6b",
          "sha1": "c78daf510c86c0951e7b618d67b058210aa163c8",
          "md5": "42acf36c4c816532facc7c039c4edc2d"
        }
      ]
    }
  ]
}
